import cv2 as cv
img=cv.imread('back1.jpg')
avg=cv.blur(img,(3,3))
gauss=cv.GaussianBlur(img,(3,3),0)
median=cv.medianBlur(img,3)
bilateral=cv.bilateralFilter(img,5,15,15)
cv.imshow('bilateral',bilateral)
cv.imshow('median',median)
cv.imshow('blur gauss',gauss)
cv.imshow('original',img)
cv.imshow('blur avg',avg)
cv.waitKey(0)